import type { Metadata } from "next";
import "./globals.css";
// import { Geist } from "next/font/google";
// import { cn } from "@/lib/utils";
import AsideNav from "@/components/navigation/aside-nav";
import { TooltipProvider } from "@/components/ui/tooltip";
import { ThemeProvider } from "@/components/theme-provider";

// const geist = Geist({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      // className={cn("h-full", "font-sans", geist.variable)}
      className="h-full"
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col font-fira">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <TooltipProvider>
            <main className="flex gap-2 max-w-7xl min-w-0 w-full mx-auto">
              <div className="flex-1 min-w-0">{children}</div>
              <aside className="hidden lg:flex flex-col items-center shrink-0 p-10">
                <AsideNav />
              </aside>
            </main>
          </TooltipProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
