import type { Metadata } from "next";
import { Fira_Code } from "next/font/google";
import "./globals.css";
import AsideNav from "@/components/navigation/aside-nav";
import { TooltipProvider } from "@/components/ui/tooltip";
import { ThemeProvider } from "@/components/theme-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const firaCode = Fira_Code({
  subsets: ["latin"],
});

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`h-full ${firaCode.className}`}
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col ">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <TooltipProvider>
            <main className="flex gap-2 max-w-7xl min-w-0 w-full mx-auto">
              <div className="flex-1 min-w-0">{children}</div>
              <aside className="hidden lg:flex flex-col items-center shrink-0 p-10">
                <AsideNav />
              </aside>
            </main>
          </TooltipProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
